Repository jenkinsci/design-library-plugin, pull requests merged in 2022-05, with the labels that each got.

#43 Improve home page appearance and performance
  src/main/resources/images/symbols/sunburst.svg
  src/main/resources/io/jenkins/plugins/designlibrary/Root/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/sample.css
Labels: bug

#44 Temporarily remove simplified Chinese translations
  .github/workflows/crowdin.yml
  src/main/resources/io/jenkins/plugins/designlibrary/AppBar/index_zh.properties
Labels: bug

#45 docs: Add bottom bar documentation
  src/main/resources/io/jenkins/plugins/designlibrary/AppBar/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/AppBar/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/sample.css
  src/main/webapp/AppBar/bottomAppBar.jelly
  src/main/webapp/AppBar/topAppBar.jelly
Labels: documentation

#47 Reenable cron based crowdin workflow
  .github/workflows/crowdin.yml
Labels: chore

#46 Use SCSS instead of plain CSS
  .gitignore
  .mvn_exec_node
  package-lock.json
  package.json
  pom.xml
  src/main/resources/io/jenkins/plugins/designlibrary/Root/index.jelly
  src/main/resources/lib/samples/sample.jelly
  src/main/resources/scss/abstracts/_index.scss
  src/main/resources/scss/abstracts/_overrides.scss
  src/main/resources/scss/components/_component-sample.scss
  src/main/resources/scss/components/_index.scss
  src/main/resources/scss/components/_source-block.scss
  src/main/resources/scss/pages/_colors.scss
  src/main/resources/scss/pages/_home.scss
  src/main/resources/scss/pages/_index.scss
  src/main/resources/scss/pages/_spacing.scss
  src/main/resources/scss/styles.scss
Labels: enhancement, chore

#56 Make the homepage responsive
  src/main/resources/scss/abstracts/_overrides.scss
  src/main/resources/scss/pages/_home.scss
Labels: bug, ui

#55 Revamp colors page
  package-lock.json
  package.json
  src/main/java/io/jenkins/plugins/designlibrary/Colors.java
  src/main/resources/io/jenkins/plugins/designlibrary/Colors/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Colors/index.properties
  src/main/resources/scss/abstracts/_index.scss
  src/main/resources/scss/abstracts/_overrides.scss
  src/main/resources/scss/abstracts/_typography.scss
  src/main/resources/scss/pages/_colors.scss
  src/main/resources/scss/pages/_home.scss
Labels: enhancement

#60 Add the color 'pink' to the Colors page
  src/main/java/io/jenkins/plugins/designlibrary/Colors.java
Labels: bug

#61 Gitpodify jenkins design library plugin
  .gitpod.yml
  README.md
Labels: documentation

#63 Improve gitpod config
  .gitpod.yml
Labels: documentation

#62 docs: Add toggle switch page
  src/main/java/io/jenkins/plugins/designlibrary/ToggleSwitch.java
  src/main/resources/images/symbols/toggle-switch.svg
  src/main/resources/io/jenkins/plugins/designlibrary/ToggleSwitch/index.jelly
  src/main/resources/scss/components/_component-sample.scss
  src/main/webapp/ToggleSwitch/default.jelly
  src/main/webapp/ToggleSwitch/dynamic.jelly
  src/main/webapp/ToggleSwitch/inverted.jelly
Labels: enhancement

#64 Add previous/next buttons for samples pages
  src/main/java/io/jenkins/plugins/designlibrary/UISample.java
  src/main/resources/lib/samples/sample.jelly
  src/main/resources/scss/components/_index.scss
  src/main/resources/scss/components/_previous-next-controls.scss
  src/main/resources/scss/pages/_colors.scss
Labels: enhancement, ui

#66 Minor tweak to gitpod
  .gitpod.yml
Labels: chore

#75 Remove workaround for intellij not being ready in gitpod
  .gitpod.yml
Labels: chore

#69 Improve dark/normal mode banner detection
  README.md
Labels: skip-changelog
