Repository jenkinsci/design-library-plugin, pull requests merged in 2022-04, with the labels that each got.

#27 build: Update plugin to 4.40
  Jenkinsfile
  pom.xml
Labels: dependencies

#30 Remove odd borders from background spinner
  src/main/resources/io/jenkins/plugins/designlibrary/sample.css
Labels: bugfix

#32 Update my PAT
  .github/workflows/crowdin.yml
Labels: chore

#35 Add default project name and icon for IntelliJ
  .gitignore
  .idea/.name
  .idea/icon.svg
Labels: chore
