Repository jenkinsci/design-library-plugin, pull requests merged in 2022-11, with the labels that each got.

#160 docs: improve formatting for crowdin translations
  src/main/resources/io/jenkins/plugins/designlibrary/AppBar/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Buttons/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Checkboxes/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Colors/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/JavaScriptProxy/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Select/index.properties
Labels: documentation

#163 Consistent quotes in American English `.properties` files
  src/main/resources/io/jenkins/plugins/designlibrary/Layouts/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Links/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Select/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/TextBox/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Validation/index.properties
Labels: bug

#167 Use ionicons-api version provided by bom
  pom.xml
Labels: developer

#174 Add content for HTML tooltips
  src/main/resources/io/jenkins/plugins/designlibrary/Tooltips/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Tooltips/index.properties
  src/main/resources/scss/abstracts/_typography.scss
  src/main/webapp/Tooltips/html-tooltip.jelly
  src/main/webapp/Tooltips/symbol-tooltip.jelly
  src/main/webapp/Tooltips/tooltip.jelly
Labels: enhancement
