Repository jenkinsci/design-library-plugin, pull requests merged in 2022-03, with the labels that each got.

#11 Refresh plugin
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
  src/main/java/jenkins/plugins/ui_samples/DropdownList.java
  src/main/java/jenkins/plugins/ui_samples/FormFieldValidationWithContext.java
  src/main/java/jenkins/plugins/ui_samples/HeteroList.java
  src/main/java/jenkins/plugins/ui_samples/Root.java
Labels: enhancement

#17 Update readme
  .gitignore
  README.md
  logo-dark.svg
  logo.svg
Labels: documentation

#18 Enable CD
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/jenkins-security-scan.yml
  .mvn/maven.config
  Jenkinsfile
  pom.xml
  src/main/resources/io/jenkins/plugins/designlibrary/Root/index.jelly
Labels: enhancement

#19 Use the up to date description for the update center
  pom.xml
  src/main/resources/index.jelly
Labels: enhancement

#21 Bump baseline to the first release shipping mandatory core components
  pom.xml
Labels: bugfix

#22 Provide initial translation for home view
  src/main/resources/io/jenkins/plugins/designlibrary/Root/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Root/index.properties
Labels: enhancement

#23 Run crowdin workflow cron based
  .github/workflows/crowdin.yml
Labels: chore
