Repository jenkinsci/design-library-plugin, pull requests merged in 2022-08, with the labels that each got.

#105 Add a link to weekly.ci.jenkins.io
  README.md
Labels: documentation

#106 Switch to renovate for NPM deps
  .github/dependabot.yml
  Jenkinsfile
  renovate.json
Labels: chore

#115 docs: Add ionicons api documentation
  pom.xml
  src/main/resources/io/jenkins/plugins/designlibrary/Symbols/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Symbols/index.properties
  src/main/webapp/Symbols/symbol-ionicons-reference.jelly
Labels: enhancement

#118 feat: Use ionicons api for core symbols
  src/main/resources/io/jenkins/plugins/designlibrary/AppBar/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Buttons/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Symbols/index.jelly
  src/main/resources/lib/samples/sample.jelly
Labels: enhancement

#121 Update library to use new button classes
  pom.xml
  src/main/resources/io/jenkins/plugins/designlibrary/Buttons/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/sample.js
  src/main/resources/lib/samples/sample.jelly
  src/main/resources/scss/components/_previous-next-controls.scss
  src/main/webapp/Buttons/copyButton.jelly
  src/main/webapp/Buttons/default.jelly
  src/main/webapp/Buttons/destructive.jelly
  src/main/webapp/Buttons/primary.jelly
  src/main/webapp/Buttons/symbolButton.jelly
  src/main/webapp/Buttons/tertiary.jelly
Labels: enhancement
