Repository jenkinsci/design-library-plugin, pull requests merged in 2023-04, with the labels that each got.

#248 Fix type error on textbox page
  src/main/resources/io/jenkins/plugins/designlibrary/TextBox/index.jelly
Labels: bug

#249 Remove usage of `l:js`
  src/main/resources/io/jenkins/plugins/designlibrary/Notifications/index.jelly
Labels: internal

#250 Drop all usages of .app-component-sample and <code /> elements
  src/main/resources/io/jenkins/plugins/designlibrary/Buttons/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Checkboxes/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Checkboxes/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Checkboxes/index_fr.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Checkboxes/index_pt.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Checkboxes/index_zh.properties
  src/main/resources/io/jenkins/plugins/designlibrary/File/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/File/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/JavaScriptProxy/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Notifications/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Progress/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Radios/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Select/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Spacing/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Symbols/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Table/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/TextBox/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/ToggleSwitch/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Tooltips/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Validation/index.jelly
  src/main/resources/scss/abstracts/_overrides.scss
  src/main/resources/scss/components/_component-group.scss
  src/main/resources/scss/components/_component-sample.scss
  src/main/resources/scss/components/_index.scss
  src/main/resources/scss/components/_source-block.scss
  src/main/webapp/TextBox/codemirror.jelly
Labels: enhancement

#254 Run renovate monthly
  .github/renovate.json
Labels: chore
