Repository jenkinsci/design-library-plugin, pull requests merged in 2023-09, with the labels that each got.

#279 update hetero list sample
  src/main/java/io/jenkins/plugins/designlibrary/HeteroList.java
  src/main/resources/io/jenkins/plugins/designlibrary/HeteroList/Config/config.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/HeteroList/configure.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/HeteroList/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/HeteroList/index.properties
  src/main/webapp/HeteroList/ChoiceEntry.java
  src/main/webapp/HeteroList/Config.java
  src/main/webapp/HeteroList/Entry.java
  src/main/webapp/HeteroList/SimpleEntry.java
  src/main/webapp/HeteroList/config.jelly
Labels: enhancement

#281 TextBox -> Inputs
  src/main/java/io/jenkins/plugins/designlibrary/Inputs.java
  src/main/resources/io/jenkins/plugins/designlibrary/Inputs/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Inputs/index.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Inputs/index_fr.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Inputs/index_zh.properties
  src/main/resources/io/jenkins/plugins/designlibrary/Select/Apple/config.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/TextBox/index.properties
  src/main/resources/scss/abstracts/_overrides.scss
  src/main/webapp/Inputs/DynamicCombobox.java
  src/main/webapp/Inputs/Sample.java
  src/main/webapp/Inputs/SimpleCombobox.java
  src/main/webapp/Inputs/codemirror-html.jelly
  src/main/webapp/Inputs/codemirror-shell.jelly
  src/main/webapp/Inputs/codemirror.jelly
  src/main/webapp/Inputs/combo-box.jelly
  src/main/webapp/Inputs/dynamic-combo-box.jelly
  src/main/webapp/Inputs/example.jelly
  src/main/webapp/Inputs/number.jelly
  src/main/webapp/Inputs/password.jelly
  src/main/webapp/Inputs/sample.jelly
  src/main/webapp/TextBox/codemirror.jelly
Labels: bug

#280 refresh links page
  pom.xml
  src/main/java/io/jenkins/plugins/designlibrary/Links.java
  src/main/java/io/jenkins/plugins/designlibrary/Root.java
  src/main/resources/io/jenkins/plugins/designlibrary/Links/index.groovy
  src/main/resources/io/jenkins/plugins/designlibrary/Links/index.properties
  src/main/resources/lib/samples/sidepanel.jelly
  src/main/webapp/Links/Links.java
Labels: enhancement

#282 Fixes TypeError on "Radios" page
  src/main/resources/io/jenkins/plugins/designlibrary/Radios/index.jelly
  src/main/resources/io/jenkins/plugins/designlibrary/Validation/State/config.jelly
Labels: bug

#72 Integrate with Prism API plugin
  pom.xml
  src/main/java/io/jenkins/plugins/designlibrary/UISample.java
  src/main/resources/io/jenkins/plugins/designlibrary/sample.js
  src/main/resources/lib/samples/sample.jelly
  src/main/resources/scss/abstracts/_overrides.scss
  src/main/resources/scss/components/_source-block.scss
  src/main/webapp/Validation/sample.jelly
Labels: enhancement, do not merge
