Repository jenkinsci/design-library-plugin, pull requests merged in 2025-01, with the labels that each got.

#381 Add a link to weekly.ci.jenkins.io
  README.md
Labels: documentation

#382 Fix 'Bottom app bar' sample to not have two 'jenkins-buttons-row' containers
  src/main/resources/io/jenkins/plugins/designlibrary/AppBar/index.jelly
  src/main/webapp/AppBar/bottomAppBar.jelly
Labels: documentation

#387 Update pom.xml to match archetype and use `jenkins.baseline` property to keep bom in sync
  pom.xml
Labels: chore

#386 table resizing
  src/main/resources/io/jenkins/plugins/designlibrary/Table/index.jelly
  src/main/resources/scss/pages/_index.scss
  src/main/resources/scss/pages/_tables.scss
  src/main/webapp/Table/index.jelly
  src/test/java/ValidRelativeUrlsTest.java
Labels: developer

#385 fix margin-bottom of jenkins-form-item
  src/main/resources/io/jenkins/plugins/designlibrary/Dialogs/index.jelly
  src/main/resources/scss/components/_component-sample.scss
  src/main/resources/scss/pages/_dialogs.scss
Labels: developer
